name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      #Manual Docker Runs
      #- run: docker build --pull --rm --file "sgbd_mysql.dockerfile" --tag sgbd:latest "."
        #--tag sgbd:$(date +%s)
      #- run: docker-compose up . --file sgbd_mysql.yml --tag sgbd:$(date +%s) -d
      #Manual Docker Login
      #- run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_GITHUB }} docker.pkg.github.com
      #- run: echo ${{ secrets.DOCKER_GITHUB }} | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      # ghcr.io
      #- run: docker push ghcr.io/eloypripan/sgbd:latest
      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Log in to the Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: |
            eloypripan
            ghcr.io/${{ github.repository }}
      # my-docker-hub-namespace/my-docker-hub-repository

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: sgbd_mysql.dockerfile
          push: true
          #tags: ${{ secrets.DOCKER_USERNAME }}/sgbd:latest
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
