name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: SQL Docker image
      #run: docker build . --file sgbd_mysql.dockerfile --tag sgbd:$(date +%s)
      run: docker build --pull --rm --file "sgbd_mysql.dockerfile" --tag sgbd:latest "."
    # - name: image2
    #  run: docker-compose up . --file sgbd_mysql.yml --tag sgbd:$(date +%s) -d
