name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      #- name: Manual Docker Runs
        #run: docker build . --file sgbd_mysql.dockerfile --tag sgbd:$(date +%s)
        #run: docker build --pull --rm --file "sgbd_mysql.dockerfile" --tag sgbd:latest "."
      #- name: image2
         #run: docker-compose up . --file sgbd_mysql.yml --tag sgbd:$(date +%s) -d
      #- name: Manual Docker Login
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_GITHUB }} docker.pkg.github.com
      - run: docker push docker.pkg.github.com/eloyprian/sql/sdbd:latest
      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: sgbd_mysql.dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sgbd:latest
