name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: SQL Docker image
        #run: docker build . --file sgbd_mysql.dockerfile --tag sgbd:$(date +%s)
        run: docker build --pull --rm --file "sgbd_mysql.dockerfile" --tag sgbd:latest "."
      # - name: image2
      #  run: docker-compose up . --file sgbd_mysql.yml --tag sgbd:$(date +%s) -d
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        # run docker login -u USERNAME -p TOKEN docker.pkg.github.com
        # run docker push docker.pkg.github.com/OWNER/REPOSITORY/IMAGE_NAME:TAG_NAME

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: sgbd_mysql.dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sgbd:latest
